// src/common/constants/error-codes.const.ts

export const ERROR_CODES = {
  // Auth (DOMAIN: AUTH)
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_INVALID_TOKEN: 'AUTH_INVALID_TOKEN',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_REVOKED: 'AUTH_TOKEN_REVOKED',
  AUTH_REFRESH_TOKEN_REUSED: 'AUTH_REFRESH_TOKEN_REUSED',
  AUTH_INSUFFICIENT_PERMISSIONS: 'AUTH_INSUFFICIENT_PERMISSIONS',

  // User (DOMAIN: USER)
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_EMAIL_DUPLICATE: 'USER_EMAIL_DUPLICATE',
  USER_ACCOUNT_DISABLED: 'USER_ACCOUNT_DISABLED',

  // File (DOMAIN: FILE)
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  FILE_TYPE_NOT_ALLOWED: 'FILE_TYPE_NOT_ALLOWED',
  FILE_UPLOAD_FAILED: 'FILE_UPLOAD_FAILED',

  // Validation (DOMAIN: VALIDATION)
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  INVALID_OBJECT_ID: 'INVALID_OBJECT_ID',

  // Resource (DOMAIN: RESOURCE)
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  DUPLICATE_ENTRY: 'DUPLICATE_ENTRY',

  // System (DOMAIN: SYSTEM)
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  DATABASE_ERROR: 'DATABASE_ERROR',
  CACHE_ERROR: 'CACHE_ERROR',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',

  NOTIFICATION_SEND_FAILED: 'NOTIFICATION_SEND_FAILED',
} as const;
