// src/common/constants/error-codes.const.ts

export const ERROR_CODES = {
  // Auth (DOMAIN: AUTH)
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_INVALID_TOKEN: 'AUTH_INVALID_TOKEN',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_REVOKED: 'AUTH_TOKEN_REVOKED',
  AUTH_REFRESH_TOKEN_REUSED: 'AUTH_REFRESH_TOKEN_REUSED',
  AUTH_INSUFFICIENT_PERMISSIONS: 'AUTH_INSUFFICIENT_PERMISSIONS',
  INVALID_PASSWORD: 'INVALID_PASSWORD',

  // User (DOMAIN: USER)
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_EMAIL_DUPLICATE: 'USER_EMAIL_DUPLICATE',
  USER_ACCOUNT_DISABLED: 'USER_ACCOUNT_DISABLED',

  // File (DOMAIN: FILE)
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  FILE_TYPE_NOT_ALLOWED: 'FILE_TYPE_NOT_ALLOWED',
  FILE_UPLOAD_FAILED: 'FILE_UPLOAD_FAILED',

  // Validation (DOMAIN: VALIDATION)
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  INVALID_OBJECT_ID: 'INVALID_OBJECT_ID',
  INVALID_WORD: 'INVALID_WORD',
  INVALID_EXAMPLES_COUNT: 'INVALID_EXAMPLES_COUNT',
  INVALID_EXAMPLE_FORMAT: 'INVALID_EXAMPLE_FORMAT',
  EMPTY_EXAMPLE: 'EMPTY_EXAMPLE',
  MISSING_PRONOUNCE: 'MISSING_PRONOUNCE',
  INVALID_POS: 'INVALID_POS',
  MISSING_VI_MEANING: 'MISSING_VI_MEANING',

  // Resource (DOMAIN: RESOURCE)
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  DUPLICATE_ENTRY: 'DUPLICATE_ENTRY',

  // System (DOMAIN: SYSTEM)
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  DATABASE_ERROR: 'DATABASE_ERROR',
  CACHE_ERROR: 'CACHE_ERROR',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',

  NOTIFICATION_SEND_FAILED: 'NOTIFICATION_SEND_FAILED',

  // Study (DOMAIN: STUDY)
  STUDY_CARD_NOT_FOUND: 'STUDY_CARD_NOT_FOUND',
  STUDY_CARD_NOT_DUE: 'STUDY_CARD_NOT_DUE',
  STUDY_INVALID_RATING: 'STUDY_INVALID_RATING',

  // Listening (DOMAIN: LISTENING)
  LISTENING_EXERCISE_NOT_FOUND: 'LISTENING_EXERCISE_NOT_FOUND',
  LISTENING_ALREADY_COMPLETED: 'LISTENING_ALREADY_COMPLETED',
  LISTENING_INVALID_TYPE: 'LISTENING_INVALID_TYPE',
  LISTENING_INVALID_SCORE: 'LISTENING_INVALID_SCORE',
  LISTENING_INVALID_ACCURACY: 'LISTENING_INVALID_ACCURACY',
  LISTENING_INVALID_FLUENCY: 'LISTENING_INVALID_FLUENCY',
  LISTENING_INVALID_DURATION: 'LISTENING_INVALID_DURATION',

  // Payment (DOMAIN: PAYMENT)
  PAYMENT_NOT_FOUND: 'PAYMENT_NOT_FOUND',
  PAYMENT_CREATE_FAILED: 'PAYMENT_CREATE_FAILED',
  PAYMENT_VERIFY_FAILED: 'PAYMENT_VERIFY_FAILED',
  SUBSCRIPTION_NOT_FOUND: 'SUBSCRIPTION_NOT_FOUND',
  SUBSCRIPTION_ALREADY_ACTIVE: 'SUBSCRIPTION_ALREADY_ACTIVE',
  SUBSCRIPTION_CANNOT_CANCEL: 'SUBSCRIPTION_CANNOT_CANCEL',
  SUBSCRIPTION_GRANT_FAILED: 'SUBSCRIPTION_GRANT_FAILED',
  REFUND_FAILED: 'REFUND_FAILED',

  // AI (DOMAIN: AI)
  AI_QUOTA_EXCEEDED: 'AI_QUOTA_EXCEEDED',

  // Notification (DOMAIN: NOTIFICATION)
  NOTIFICATION_NOT_FOUND: 'NOTIFICATION_NOT_FOUND',

  // Study Session (DOMAIN: STUDY_SESSION)
  STUDY_SESSION_ALREADY_ACTIVE: 'STUDY_SESSION_ALREADY_ACTIVE',
  STUDY_SESSION_NOT_FOUND: 'STUDY_SESSION_NOT_FOUND',

  // Session (DOMAIN: SESSION)
  SESSION_NOT_FOUND: 'SESSION_NOT_FOUND',

  // Feature Flag (DOMAIN: FEATURE)
  FEATURE_FLAG_NOT_FOUND: 'FEATURE_FLAG_NOT_FOUND',

  // Public (DOMAIN: PUBLIC)
  PUBLIC_USER_NOT_FOUND: 'PUBLIC_USER_NOT_FOUND',

  // Audit Log (DOMAIN: AUDIT_LOG)
  AUDIT_LOG_NOT_FOUND: 'AUDIT_LOG_NOT_FOUND',

  // Report (DOMAIN: REPORT)
  REPORT_NOT_FOUND: 'REPORT_NOT_FOUND',
  REPORT_ALREADY_RESOLVED: 'REPORT_ALREADY_RESOLVED',
  REPORT_INVALID_TARGET: 'REPORT_INVALID_TARGET',

  // Favorite (DOMAIN: FAVORITE)
  FAVORITE_NOT_FOUND: 'FAVORITE_NOT_FOUND',
  FAVORITE_ALREADY_EXISTS: 'FAVORITE_ALREADY_EXISTS',

  // Activity (DOMAIN: ACTIVITY)
  USER_ACTIVITY_NOT_FOUND: 'USER_ACTIVITY_NOT_FOUND',

  // Bulk Operations (DOMAIN: BULK)
  BULK_OPERATION_FAILED: 'BULK_OPERATION_FAILED',
  BULK_CARD_NOT_FOUND: 'BULK_CARD_NOT_FOUND',
  BULK_ACCESS_DENIED: 'BULK_ACCESS_DENIED',

  // Rate Limit (DOMAIN: RATE_LIMIT)
  RATE_LIMIT_INFO_FETCH_FAILED: 'RATE_LIMIT_INFO_FETCH_FAILED',

  // Pusher (DOMAIN: PUSHER)
  PUSHER_AUTH_FAILED: 'PUSHER_AUTH_FAILED',
  PUSHER_CHANNEL_ACCESS_DENIED: 'PUSHER_CHANNEL_ACCESS_DENIED',

  // Jobs (DOMAIN: JOB)
  JOB_NOT_FOUND: 'JOB_NOT_FOUND',

  // 2FA (DOMAIN: TWO_FACTOR)
  TWO_FACTOR_ALREADY_ENABLED: 'TWO_FACTOR_ALREADY_ENABLED',
  TWO_FACTOR_NOT_ENABLED: 'TWO_FACTOR_NOT_ENABLED',
  TWO_FACTOR_REQUIRED: 'TWO_FACTOR_REQUIRED',
  TWO_FACTOR_INVALID_OTP: 'TWO_FACTOR_INVALID_OTP',
  RECOVERY_CODE_INVALID: 'RECOVERY_CODE_INVALID',

  // GDPR (DOMAIN: GDPR)
  GDPR_EXPORT_TOO_LARGE: 'GDPR_EXPORT_TOO_LARGE',
  GDPR_EXPORT_RATE_LIMITED: 'GDPR_EXPORT_RATE_LIMITED',
} as const;
