// src/common/constants/error-codes.const.ts

export const ERROR_CODES = {
  // Auth (DOMAIN: AUTH)
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_INVALID_TOKEN: 'AUTH_INVALID_TOKEN',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_REVOKED: 'AUTH_TOKEN_REVOKED',
  AUTH_REFRESH_TOKEN_REUSED: 'AUTH_REFRESH_TOKEN_REUSED',
  AUTH_INSUFFICIENT_PERMISSIONS: 'AUTH_INSUFFICIENT_PERMISSIONS',

  // User (DOMAIN: USER)
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_EMAIL_DUPLICATE: 'USER_EMAIL_DUPLICATE',
  USER_ACCOUNT_DISABLED: 'USER_ACCOUNT_DISABLED',

  // File (DOMAIN: FILE)
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  FILE_TYPE_NOT_ALLOWED: 'FILE_TYPE_NOT_ALLOWED',
  FILE_UPLOAD_FAILED: 'FILE_UPLOAD_FAILED',

  // Validation (DOMAIN: VALIDATION)
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  INVALID_OBJECT_ID: 'INVALID_OBJECT_ID',
  INVALID_WORD: 'INVALID_WORD',
  INVALID_EXAMPLES_COUNT: 'INVALID_EXAMPLES_COUNT',
  INVALID_EXAMPLE_FORMAT: 'INVALID_EXAMPLE_FORMAT',
  EMPTY_EXAMPLE: 'EMPTY_EXAMPLE',
  MISSING_PRONOUNCE: 'MISSING_PRONOUNCE',
  INVALID_POS: 'INVALID_POS',
  MISSING_VI_MEANING: 'MISSING_VI_MEANING',

  // Resource (DOMAIN: RESOURCE)
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  DUPLICATE_ENTRY: 'DUPLICATE_ENTRY',

  // System (DOMAIN: SYSTEM)
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  DATABASE_ERROR: 'DATABASE_ERROR',
  CACHE_ERROR: 'CACHE_ERROR',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',

  NOTIFICATION_SEND_FAILED: 'NOTIFICATION_SEND_FAILED',

  // Study (DOMAIN: STUDY)
  STUDY_CARD_NOT_FOUND: 'STUDY_CARD_NOT_FOUND',
  STUDY_CARD_NOT_DUE: 'STUDY_CARD_NOT_DUE',
  STUDY_INVALID_RATING: 'STUDY_INVALID_RATING',

  // Listening (DOMAIN: LISTENING)
  LISTENING_EXERCISE_NOT_FOUND: 'LISTENING_EXERCISE_NOT_FOUND',
  LISTENING_ALREADY_COMPLETED: 'LISTENING_ALREADY_COMPLETED',
  LISTENING_INVALID_TYPE: 'LISTENING_INVALID_TYPE',

  // Payment (DOMAIN: PAYMENT)
  PAYMENT_NOT_FOUND: 'PAYMENT_NOT_FOUND',
  PAYMENT_CREATE_FAILED: 'PAYMENT_CREATE_FAILED',
  PAYMENT_VERIFY_FAILED: 'PAYMENT_VERIFY_FAILED',
  SUBSCRIPTION_NOT_FOUND: 'SUBSCRIPTION_NOT_FOUND',
  SUBSCRIPTION_ALREADY_ACTIVE: 'SUBSCRIPTION_ALREADY_ACTIVE',
  SUBSCRIPTION_CANNOT_CANCEL: 'SUBSCRIPTION_CANNOT_CANCEL',
  SUBSCRIPTION_GRANT_FAILED: 'SUBSCRIPTION_GRANT_FAILED',
  REFUND_FAILED: 'REFUND_FAILED',
} as const;
